GRAPHQL {{host}}/v1/graphql
Authorization: Bearer {{key}}

{
  Get {
    ExpenseTracker_Prod_Transactions(
      limit: 5,
      tenant: "7a8e0603-dca6-474c-a0f7-34a748567aee",
      sort: {
        path: ["expense_date"],
        order: desc
      }
    ) {
      description
    }
  }
}