< {%
 request.variables.set("dryRun", "false")
 %}

POST {{tolkienAiServer_host}}/data/ingest
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "source": "SILMARILLION",
  "dryRun": {{dryRun}}
}