< {%
 request.variables.set('className', 'ExpenseTracker_Prod_Transactions')
 request.variables.set('id', 'b0ac458a-1714-4486-979b-ff666b78a765')
 %}

GET {{host}}/v1/objects/{{className}}/{{id}}
Authorization: Bearer {{key}}