# Get userId from the user-info.http endpoint on keycloak
< {%
 request.variables.set('transactionId', 'b0ac458a-1714-4486-979b-ff666b78a765')
 %}

GET {{expenseTrackerApi_host}}/ai/admin/all-tenants/embedding/{{userId}}/transactions/{{transactionId}}
Authorization: Bearer {{token}}