POST {{keycloak_host}}/realms/{{keycloak_realm}}/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded

client_id = {{postman_clientId}} &
client_secret = {{postman_clientSecret}} &
token = {{token}}